export const EXPECTED_ROLEPACK_COUNT = 500;

export const DEPARTMENTS = [
  "Gestão Executiva & Estratégia",
  "Operações & Eficiência",
  "Finanças, Contabilidade & Tesouraria",
  "Recursos Humanos & Talentos",
  "Vendas, Business Development & Receita",
  "Marketing, Growth & Performance",
  "Atendimento ao Cliente & Customer Success",
  "Tecnologia, Engenharia & IT",
  "Produto, UX & Design",
  "Legal, Compliance & Governança",
  "Procurement, Compras & Fornecedores",
  "Logística, Cadeia de Mantimentos & Armazém",
  "Qualidade, Processos & Auditoria",
  "Inovação, R&D & Inteligência Competitiva",
  "Comunicação Corporativa & PR",
  "Data, Analytics & Business Intelligence",
  "Segurança da Informação & Cibersegurança",
  "Instalações, Imobiliário & Serviços Gerais",
  "Sustentabilidade, ESG & Impacto Social",
  "Relações Internacionais & Expansão",
  "Gestão de Risco & Continuidade de Negócio",
  "Venda a Retalho & E-Commerce",
  "B2B Account Management",
  "Formação, EdTech & Conhecimento",
  "Saúde Corporativa & Segurança no Trabalho",
  "Imobiliário & Gestão de Activos",
  "Turismo, Hotelaria & Eventos",
  "Construção, Engenharia Civil & Obras",
  "Indústria, Manufatura & Produção",
  "Agricultura, Agropecuária & Bio-Indústria",
  "Energia, Utilities & Recursos Naturais",
  "Serviços Financeiros, Banca & Seguros",
  "Telecomunicações & Redes",
  "Mídia, Conteúdo & Entretenimento",
  "Sector Público, Governo & Regulação",
  "ONG, Sem Fins Lucrativos & Fundações",
  "Saúde, Clínicas & Life Sciences",
  "Educação Superior & Investigação",
  "Desporto, Fitness & Bem-Estar",
  "Serviços Jurídicos & Advocacia",
  "Moda, Design de Produto & Estilo",
  "Automóvel, Mobilidade & Transportes",
  "Ciber-Defesa & Proteção da Informação",
  "Especialistas em IA Empresarial & Agentes"
] as const;
